### ISSUE TITLE
超链导向页面时，如何其页面内容只写了“page部分”，则脚本报错

### ISSUE THREAD

**Issue by windbell2live** [lihongxun945/light7#14]
F7的超链页面内容，可以只写<div class="view"><div class="page">....</div></div>的，
在我从f7将项目迁移L7时，这样时，脚本会报错
  Router.prototype.parseXHR 里的
    var html  = response.match(/<body[^>]*>([\s\S.]*)<\/body>/i)[1];
报错：Uncaught TypeError: Cannot read property '1' of null

将模板页（含有css,jss等 和主UI框架)套上之后 正常

**Comment by djjandyhl** [comment]
这个我也遇到了。ajax请求的页面，只有page部分就会报错。把整个页面写全，引入L7的JS,CSS等文件就不会报错。

**Comment by lihongxun945** [comment]
我知道原因了，下一次发布就会修复这个问题

**Comment by lihongxun945** [comment]
0.0.4 已发布
