### ISSUE TITLE
更新v0.0.4后，以前的工具栏切换地址出现问题。

### ISSUE THREAD

**Issue by djjandyhl** [lihongxun945/light7#17]
更新v0.0.4后，在微信浏览器中：以前的工具栏nav中的多个标签切换 （如 a class="tab-item" href="index.html" external ） 切换到其他页面会跳转回来，导致页面不能跳转走。但是在桌面chrome里测试好像没问题。

**Comment by lihongxun945** [comment]
我在safari中重现了这个问题，在 0.0.5 中会修复， 等发布之后你可以再试一下
