### ISSUE TITLE
将路由禁用后,A页面滚动条拉到底部,然后跳转到B,然后返回A,结果A页面刷新了,并没有保持滚动条在底部

### ISSUE THREAD

**Issue by bigmeow** [lihongxun945/light7#18]
如题

**Comment by lihongxun945** [comment]
因为禁用路由之后就是浏览器的原生的跳转，本来就没有这个功能

**Comment by geekv** [comment]
No No  这个就是浏览器的功能   会记住上一个页面的状态   点击返回时就恢复上一个页面的状态  你随便开一个网站看看就知道了

**Comment by lihongxun945** [comment]
是不是因为你不是后退，而是从B跳转到A

**Comment by geekv** [comment]
我的返回按钮写的是history.go(-1),在电脑上点浏览器的后退也无效  你直接看我这例子呗  http://bigmeow.cn/demo/maicai/   首页列表下拉   然后点一个菜品看看详情  然后返回

**Comment by lihongxun945** [comment]
你的A页面是动态加载的内容，不要用Ajax页面，用内联的

**Comment by lihongxun945** [comment]
也不对，这种情况浏览器的原生后退也没用啊，你的页面内容都是动态加载的
