### ISSUE TITLE
alert 显示不出来

### ISSUE THREAD

**Issue by tomsean** [lihongxun945/light7#19]
$.alert('Here goes alert text');显示不出来，经调试light7,问题定位在light7执行的时候var defaults =  $.modal.prototype.defaults  = {
        modalButtonOk: '确定',
        modalButtonCancel: '取消',
        modalPreloaderTitle: '加载中',
        modalContainer : document.body 
    };的时候document.body为空

**Comment by lihongxun945** [comment]
即将发布的v0.1.0 已经修复
