### ISSUE TITLE
 radio,checkbox和开关按钮，在手机浏览器里卡顿延迟

### ISSUE THREAD

**Issue by fadesky** [lihongxun945/light7#20]
radio,checkbox和开关按钮，在手机浏览器里感觉卡顿延迟，电脑模拟器里没问题。
另外，如何捕获这些按钮状态改变的事件？

**Comment by lihongxun945** [comment]
这是之前改动fastclick改出的一个bug，当时是为了解决可选列表无法选择的bug。在下一个版本 v0.1.0 会修复这个问题。
