### ISSUE TITLE
侧边栏点击链接（ajax加载），如果链接页是当前页，则无法再次打开侧边栏（似乎是没触发click）。虽然刷新页面又可以了。

### ISSUE THREAD

**Issue by troublezzb** [lihongxun945/light7#23]
如：首页点击【菜单】打开侧边栏，点击<a href="index.html" class="item-link close-panel">【首页】</a>。此时再次点击【菜单】没有反应。
2015-12-21下午 从英文官网下载的v0.1.0

环境：使用chrome模拟移动设备
现象：浏览器历史纪录新增一条url一样的记录。

环境：红米note3（微信/uc/自带浏览器）
现象：在上面的基础上，还出现了：从侧边栏进入其他二级页面（只有【返回】按钮），点击【返回】首页后，也出现了无法打开侧边栏的情况（测试几十次，偶发率大概90%，可能我测晕了）。

**Comment by lihongxun945** [comment]
更新了 v0.3.0 你看看这个问题是不是不存在了

**Comment by troublezzb** [comment]
好像bug还存在
