### ISSUE TITLE
exec grunt to compile all source file

### ISSUE THREAD

**Issue by aetherwu** [lihongxun945/light7#29]
light7-master $ grunt 
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

**Comment by aetherwu** [comment]
Here is what I've tried next:

light7-master $ npm install grunt --save-dev
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
grunt@0.4.5 node_modules/grunt
├── which@1.0.9
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── exit@0.1.2
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── grunt-legacy-log@0.1.3 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)
├── nopt@1.0.10 (abbrev@1.0.7)
├── glob@3.1.21 (inherits@1.0.2, graceful-fs@1.2.3)
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.3)
├── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)

light7-master$ grunt
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'load-grunt-tasks'
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.

**Comment by lihongxun945** [comment]
Sorry, this lib is writen for frontend developer. I think every frontend deveopler should know how to use grunt and npm.

You should run `npm install` before you can use `grunt`.

I will update the readme file about how to install grunt, thanks.
