### ISSUE TITLE
A more precise and user friendly getting-started page

### ISSUE THREAD

**Issue by aetherwu** [lihongxun945/light7#30]
Where to get 
script type='text/javascript' src='js/zepto.min.js' charset='utf-8

Where to find
link rel="stylesheet" href="css/light7-extend.min.css
script type='text/javascript' src='js/light7-extend.min.js' charset='utf-8'

**Comment by lihongxun945** [comment]
Sorry, I will update the get start page this weekend.

**Comment by lihongxun945** [comment]
You can get Zepto on http://zeptojs.com/

And the light7-extend.js is renamed to light7-swiper.js. Here is the document http://light7.org/extends/#swiper
