### ISSUE TITLE
toast 不居中

### ISSUE THREAD

**Issue by lihongxun945** [lihongxun945/light7#38]
toast文案较长的时候 不居中。

**Comment by YacoZhu** [comment]
@lihongxun945  求解决。目前没有解决方案吗？

**Comment by lihongxun945** [comment]
@YacoZhu  v0.4.2 已经解决这个问题

**Comment by nmll** [comment]
引入jquery 还是没有居中 zepto就可以 会不会是outerWidth不一样

**Comment by lihongxun945** [comment]
@nmll 你是引用的 v0.4.2 版本么。这个版本才修复了居中问题

**Comment by nmll** [comment]
刚刚检查了下 
marginLeft: - Math.round(modal.outerWidth() / 2 + 32 / 2)  + 'px'
现在引入这个可以了。。  这个我看是删除的代码，我再看看吧

**Comment by lihongxun945** [comment]
这个代码是错的，你看我最新的代码
