### ISSUE TITLE
浏览器刷新路由问题

### ISSUE THREAD

**Issue by chenzm080** [lihongxun945/light7#44]
内联路由方式
由页面a 通过 <a href="#b">路由到b块 能执行b块的pageInit
这时，刷新浏览器页面，页面能显示b块内容，可是没有调用到pageInit，这是何解？
有没有办法获取当前路由？

**Comment by lihongxun945** [comment]
你把你的页面链接或者代码发出来么，你这样描述看不出问题

**Comment by chenzm080** [comment]
`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>我的生活</title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" href="/favicon.ico">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" href="assets/css/light7.css">
    <link rel="stylesheet" href="assets/css/light7-swiper.min.css">
</head>
<body>

    <nav class="bar bar-tab">
        <a class="tab-item active" href="#page-home">
            <span class="icon icon-home"></span>
            <span class="tab-label">首页</span>
        </a>
        <a class="tab-item" href="#page-goods" id="home_goods">
            <span class="icon icon-me"></span>
            <span class="tab-label">我</span>
        </a>
    </nav>
<div class="page-group">
    <div class="page page-home" id="page-home">
        <header class="bar bar-nav">
            <a class="icon icon-settings pull-left open-panel"></a>
            <a class="button button-link button-nav pull-right open-popup" data-popup=".popup-about">
                About
                <span class="icon icon-menu"></span>
            </a>
            <h1 class="title">Light7 Mall</h1>
        </header>
        <div class="content">
        <p>Hello page home!</p>
        </div>
    </div>
    <div class="page page-goods" id="page-goods">
        <header class="bar bar-nav">
            <h1 class="title">商店列表</h1>
        </header>
        <div class="content infinite-scroll" data-distance="50">
            <div class="list-block">
                <ul id="someone_list">
                    <li class="item-content item-link" v-for="item in items" v-on:click="removeTodo(item)">
                        <div class="item-media"><i class="icon icon-f7"></i></div>
                        <div class="item-inner">
                            <div class="item-title">@{{ item.company }}</div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="infinite-scroll-preloader hidden">
                <div class="preloader"></div>
            </div>
        </div>
    </div>
</div>
<script type='text/javascript' src='assets/js/jquery-2.2.1.min.js' charset='utf-8'></script>
<script type='text/javascript' src='assets/js/light7.min.js' charset='utf-8'></script>
<script type='text/javascript' src='assets/js/light7-swiper.min.js' charset='utf-8'></script>
<script>
$(function(){
    $(document).on('pageInit',function(e,pageId,$page){
        console.log(e);
        console.log(pageId);
        console.log($page);
    });
});
</script>
</body>
</html>`

我在页面的底部打印，页面刷新时没有打印记录
我点击“首页”或“我”时就会打印出来了@lihongxun945

**Comment by chenzm080** [comment]
或者这么问，浏览器刷新页面时，没有调用到pageInit

**Comment by lihongxun945** [comment]
是不是因为你的页面结构不对，必须要有一个 `.page` 容器，并且要有一个`id`属性。你可以对比下 [demos](http://light7.org/demos)

**Comment by lihongxun945** [comment]
@chenzm080  刷新页面的时候是确定有 pageInit 事件的。

**Comment by luo1x** [comment]
@lihongxun945 当用$.router.loadPage切换到另一个page的时候刷新浏览器，会导致返回按钮$.router.back事件不起作用
