### ISSUE TITLE
如何用bower安装

### ISSUE THREAD

**Issue by jiaowochunge** [lihongxun945/light7#45]
是 bower install https://github.com/lihongxun945/light7.git#build --save 吗？后面加上#build吗？我看你在其他issue中提到build分支是编译过的。我刚接触前端，基本完全不懂

**Comment by jiaowochunge** [comment]
我感觉应该是这样。但是安装完后，_site和less目录有用吗？是不是应该忽略掉的啊？

**Comment by lihongxun945** [comment]
我没有发布到 `bower`，只能用`npm`安装。而且官网上写了应该怎么安装了。 里面也不存在 `_site` 和 `less` 目录，只有一个 `dist` 目录

**Comment by jiaowochunge** [comment]
实际上我已经使用bower安装了。就是我上面敲的命令安装的，貌似也能跑。问题就是我在2楼说的情况。因为我看到你的代码下面有个bower.json文件，所以就这么装了。  
"ignore": [
    "_config.yml",
    ".travis.yml",
    "CNAME",
    "CONTRIBUTING.md",
    "docs"
  ]
这是那个文件中的配置。也许可以考虑把_site和less目录都忽略了

**Comment by lihongxun945** [comment]
其实那个只是没有删的无用文件，考虑到以后一年会发布到bower，所以就没删。我自己确实没有往bower上发过，可能是别人发的
