### ISSUE TITLE
group buttons 对 tab-link 类存在的疑惑

### ISSUE THREAD

**Issue by jiaowochunge** [lihongxun945/light7#46]
查看文档时，http://123.56.245.102/components/#bars 这里 ‘带标签页’ 的按钮组，我复制代码后，发现点击事件无效，不跳转。
我尝试把tab-link类去掉，结果就跳转成功了。
文档继续往下，http://123.56.245.102/components/#buttons 这下面的按钮组，是没有 tab-link 这个类的。总之这个类把我折腾了一下。所以 tab-link 类是个坑？
请问有没有qq群方便交流的？

**Comment by lihongxun945** [comment]
你可以加入这个群讨论 255389987
你说的问题 等我这周末看一下

**Comment by jiaowochunge** [comment]
是我鱼了。需要 tabs 类配合，设置对应id。http://123.56.245.102/examples/light7-mall/detail 商城demo中有用法。
