### ISSUE TITLE
2个关于路由的问题，比较常用的

### ISSUE THREAD

**Issue by wltj920** [lihongxun945/light7#47]
前提，有3个页面A->B->C，3个页面都是独立的页面，并且在.page上设置了不同的ID。
A通过$.router.loadPage('B');到B，B再通过$.router.loadPage('C');到C

1、C页面在执行了一段JS后，用$.router.reloadPage();把页面刷新了，使用$.router.back();执行一次，没有任何反应，再执行一次，转向了A页面。。。这个是BUG吗？

2、B页面执行了一段JS后，用$.router.back();成功回到了A页面，但是在返回之前能否执行A页面的方法，或者让A页面$.router.reloadPage();一下呢？

这两大问题，麻烦大神解答一下啊

**Comment by lihongxun945** [comment]
感谢反馈。

- 第一个问题确实是bug，`$.router.reloadPage` 会导致前一个历史异常，下一个版本会修复这个问题。
- 第二个问题，请看文档，返回到A页面的时候会触发 `pageReinit` 事件的

**Comment by lihongxun945** [comment]
这个bug已经修复 v0.4.2
