### ISSUE TITLE
链接上使用external，点击.back返回，会undefined

### ISSUE THREAD

**Issue by guoshanche** [lihongxun945/light7#49]
同标题

**Comment by xyqfer** [comment]
`external ` 已经不受路由控制了吧？应该要把返回的链接写到 `.back` 的 `href` 里？

**Comment by lihongxun945** [comment]
`.back` 链接确实不支持 `external` 属性的，如果你是想点击返回直接跳转到一个页面，不加 `.back` 就行了。如果希望在无法返回的时候才跳转指定页面，那么把链接写在 `href` 中就好了

**Comment by lihongxun945** [comment]
`.back` 和 `.external` 不能一起用。。。

**Comment by elenjoy-wlz** [comment]
我描述不清楚吧，我重新说一下：

A页面一个链接带`.external`类，点击该链接去到B页面，B页面有一个`.back`类，点击想回到A页面，但是，就undefined 了。

**Comment by lihongxun945** [comment]
`undefined` 的意思是报错了么？可以把报错信息贴出来么，还有A页面和B页面的链接的代码也贴一下 我看看

**Comment by elenjoy-wlz** [comment]
A页面
http://localhost/b/index.html
` <li>
			            <a href="base.html" class="item-link item-content" external>
			              <div class="item-inner">
			                <div class="item-title">页面基本结构（原生）</div>
			              </div>
			            </a>
			          </li>`

B页面
http://localhost/b/base.html
`<header class="bar bar-nav">
                <a class="button button-link button-nav pull-left back">
			      <span class="icon icon-left"></span>返回
			    </a>
                <h1 class="title">标题</h1>
            </header>`

点击返回
http://localhost/b/undefined

**Comment by lihongxun945** [comment]
好的，太感谢了，我自己复现一下试试

**Comment by lihongxun945** [comment]
已经复现出问题，下一个版本会修复这个问题。

不过你的用法也有问题，`.back` 链接上应该加一个 `href` 属性，这样万一路由不知道怎么会退（比如用户直接打开这个页面，就无法回退），直接跳转到 `href` 指定的页面。

**Comment by guoshanche** [comment]
好的，明白了

**Comment by lihongxun945** [comment]
v0.4.2 已经解决这个问题
