### ISSUE TITLE
swiper版本过低，导致轮播图首尾不平滑衔接（即使设置了loop:true）

### ISSUE THREAD

**Issue by troublezzb** [lihongxun945/light7#53]
【问题现象：】轮播图自动滚动(autoplay:1000)，没设置loop:true也自动循环（原因未知）。
问题是：最后一张到第一张的过渡效果，类似倒带效果。
能不能一直平滑过渡呢？
【环境：】使用chrome模拟移动设备
【测试：】
①设置loop:true：发现部分解决了问题，但第一张到第二张的过渡效果又回到了上面的问题。
②关闭自动滚动（autoplay:false）：鼠标拖动最后一张，它的过渡也是有点卡顿的。
③套swiper 3.3.1：问题解决，首尾衔接很平滑，暂未发现其它问题。

**Comment by lihongxun945** [comment]
V0.4.3 版本会把Swiper更新到 3.3.1

**Comment by troublezzb** [comment]
问题已解决。
