### ISSUE TITLE
日期组件在微信开发中（安卓环境）会调用输入法，如何禁用

### ISSUE THREAD

**Issue by ArleyJoe** [lihongxun945/light7#54]
请问下，在安卓环境下做微信开发，添加了日期组件，使用的是input。但是点击input时间一直会调用手机的输入法，自己添加的readonly也不起作用，这个是什么问题，如何解决？谢谢！

**Comment by lihongxun945** [comment]
这个问题其实是安卓对 `readonly` 支持有bug。建议不要直接用 input ，而是绑定在一个隐藏的input上，然后用一个div伪装成input，点击div的时候通过JS打开日期组件。

**Comment by ArleyJoe** [comment]
这个尝试过了，通过div调用出来了但是组件中的点击事件（选定日期、next、prev等）都不响应，在查找，还没找到问题，这个是部分函数中的参数e的问题吗？

**Comment by lihongxun945** [comment]
在隐藏的input上初始化，不要直接在div上初始化。这个方式我在自己的项目中就是这样用的

**Comment by ArleyJoe** [comment]
恩，解决了，不过把初始化的input的判断限定给去除了，用了一div。谢谢！

**Comment by lihongxun945** [comment]
V0.4.3 已经修复了这个问题
