### ISSUE TITLE
页面存在两个省市选择框，点第二个会重置第一个

### ISSUE THREAD

**Issue by dojason** [lihongxun945/light7#57]
页面上有两个省市选择框：1，在第一个选择框上，先选省，再选市，点OK；2，再点击第二个选择框，会重置第一个选择框里面的文本

**Comment by nmll** [comment]
广东 深圳 福田区 我设置这个默认值 第一次会变成 广东 广州 越秀区，二次进来后又好了。刷新后，又来了

**Comment by dojason** [comment]
我也一样，省市区三级的时候，有时候默认无法展开区的选择。

**Comment by lihongxun945** [comment]
上述反馈的两个问题都会在 v0.4.3 版本修复。

**Comment by nmll** [comment]
@lihongxun945  透露下0.4.3啥时发布

**Comment by lihongxun945** [comment]
V0.4.3 已经发布
