### ISSUE TITLE
路由器会加载 href="javascript:;" 导致报错

### ISSUE THREAD

**Issue by fengweb** [lihongxun945/light7#59]
如题！`<a href="javascript:;" class="m-btn">加载更多图片</a>`

`

**Comment by lihongxun945** [comment]
这是由于路由器没有排除这种情况，导致会去加载这个页面而报错。下一个版本会修复这个问题。

目前可以通过加上 `class='external'` 来解决。

**Comment by lihongxun945** [comment]
V0.4.3 已经解决
