### ISSUE TITLE
谷歌浏览器出现 Uncaught SecurityError

### ISSUE THREAD

**Issue by 804145113** [lihongxun945/light7#69]
貌似只有谷歌浏览器才出现 Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL，网上搜索了下，说是谷歌的新的安全特性，本人刚接触前端不久，在light7中不知如何解决这个问题？
![error222](https://cloud.githubusercontent.com/assets/5610994/14097766/26e34892-f5a7-11e5-8c16-c993d9daccd3.png)

**Comment by lihongxun945** [comment]
在服务器中打开，不要双击文件打开

**Comment by 804145113** [comment]
额，谢谢。
