### ISSUE TITLE
切换toolbar菜单路由会重复创建page

### ISSUE THREAD

**Issue by fangjj** [lihongxun945/light7#8]
路由加载ajax页面，会重复创建page

**Comment by fangjj** [comment]
![bug](https://cloud.githubusercontent.com/assets/15318800/10928610/28e54170-82e5-11e5-955d-577f8592020d.png)

**Comment by lihongxun945** [comment]
那是因为你真的又加载了一个同样的page吧

**Comment by lihongxun945** [comment]
如果你是想返回上一页，用返回按钮，不要加载一个新页面

**Comment by fangjj** [comment]
是菜单切换，怎么解决，
![page](https://cloud.githubusercontent.com/assets/15318800/10929843/880aefe8-82f3-11e5-833d-e0ece064d7f8.png)

**Comment by lihongxun945** [comment]
我正在解决这个问题，计划月内发一个新版本，主要解决就是这种工具栏切换的问题

**Comment by lihongxun945** [comment]
@fangjj  已经解决了，参考 0.0.4 的更新日志 http://light7.org/changelog/
