### ISSUE TITLE
群主加个通知浮动提示

### ISSUE THREAD

**Issue by JHeLiu** [lihongxun945/light7#9]
群主加个通知浮动提示,
群主加个通知浮动提示,
群主加个通知浮动提示,
重要的事说3遍

**Comment by lihongxun945** [comment]
描述清楚一点，什么样的浮动提示

**Comment by JHeLiu** [comment]
额，我发个链接。。不好描述。你去看看
http://frozenui.github.io/frozenui/demo/poptips.html

**Comment by fangjj** [comment]
类似，toast，可以提供上中下位置参数么。

**Comment by fangjj** [comment]
toast，最好点击出现提示，没有消失不要创建新的。

**Comment by lihongxun945** [comment]
已上线 http://light7.org/components/#notification
